/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_nela_jniLibrary_NelaLoginJNI */

#ifndef _Included_com_nela_jniLibrary_NelaLoginJNI
#define _Included_com_nela_jniLibrary_NelaLoginJNI

#include "../../../../../../Android/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni_md.h"
#include "../../../../../../Android/android-ndk-r20b/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nela_jniLibrary_NelaLoginJNI
 * Method:    Nela_login
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nela_jniLibrary_NelaLoginJNI_Nela_1login
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
